services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:3000
      - UNTAPPD_CLIENT_ID=jassqueen
      - UNTAPPD_CLIENT_SECRET=jassqueen
      - AUTH_SECRET=AUTHYBOY
      - JWT_SECRET=topsecret

  backend:
    build: ./backend
    volumes:
      - "./database.db:/app/database"
