services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:3000

  backend:
    build: ./backend
    environment:
      - UNTAPPD_BASE_URL=https://api.untappd.com/v4/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
