services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:3000

  backend:
    build: ./backend
    environment:
      - UNTAPPD_BASE_URL=https://api.untappd.com/v4/

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=winmonopolet_dev
      - POSTGRES_USER=winmonopolet_dev
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
